# Generated by Django 4.2.7 on 2026-04-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_slug_enrollment_progress_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='certificate_unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
